### ISSUE TITLE
Jobs hanging and not being picked up by runners despite using '[runs-on,runner=2cpu-linux-x64]'

### ISSUE THREAD

**Issue by ooaklee** [runs-on/runs-on#102]
I want to start by saying that Runs-on is a game-changer! Thanks for your efforts

I wanted to open this ticket to let you know that we're experiencing hanging jobs with just one of our repos despite using the latest release - v2.3.2.  

When setting our runners with `runs-on: runs-on,runner=2cpu-linux-x64`, our jobs for the repo are in a constant pending state, despite our repository showing that we have A LOT of available runners, some of which end up going off line because of inactivity

![image](https://github.com/runs-on/runs-on/assets/10158645/5a079d94-50e0-4bb3-8787-d8d13e808881)

As you can see, all the runners are provisioned with the label `runs-on,runner=2cpu-linux-x64` (which will work for the other repos but not the repo I am referring to in this issue). When I manually add the individual labels `runs-on` and `runner=2cpu-linux-x64` label to an idle runner (shown below)

![image](https://github.com/runs-on/runs-on/assets/10158645/ce74b719-454d-47d9-9b67-780fc70aa033)

It picks up one of the queued jobs from the above.

The behaviour described above suggests that the repo in question might be a part of the `GitHub  A/B testing` you shared in recent comms. 

When we try the suggested workaround of using `runs-on: [runs-on,runner=2cpu-linux-x64]`, our job continues to hang with the following

```
Requested labels: runs-on, runner=2cpu-linux-x64
Job defined at: surgeventures/app-b2c-spa/.github/workflows/ci.yaml@refs/pull/4470/merge
Waiting for a runner to pick up this job...
```

> Note the space between the labels,

When looking at the runners that are provisioned by runs-on, I get the following: 

![image](https://github.com/runs-on/runs-on/assets/10158645/5e772a61-ab6a-4c12-bf3f-086023d8d43f)

Is there anything else we can try on our side to get this resolved? When declaring our runner with `[runs-on,runner=2cpu-linux-x64]`, is it fair to assume that the runners provision should have individual labels `runs-on` and `runner=2cpu-linux-x64`? If so, would you be able to push a hotfix? 

Thank you again for your amazing product! I look forward to hearing from you.

**Comment by crohr** [comment]
Hi @ooaklee, based on the screenshots you are sharing, the runners still get a single label assigned, otherwise they would appear as 2 different badges. So something is not correct yet. I would make sure to delete all the runners with the single badge label, cancel all queued jobs, and then retry. You can also reach out at cyril@runs-on.com so that we can schedule a call if needed, to have a look together.

**Comment by ooaklee** [comment]
Hey @crohr, thanks for such a prompt response! Ok, I will give it a try. To confirm:

- Do you want me to terminate all the runners at the repository level or the organisation level?
- Also, with the queue, would it be the queue at the repository level or the organisation level?

I will also drop you an email

**Comment by crohr** [comment]
@ooaklee RunsOn only launches runners at the repository level, so you should terminate those.

**Comment by crohr** [comment]
In the end this was a combination of the new [silent labelling change from GitHub](https://runs-on.com/guides/troubleshoot/#all-jobs-are-queued-indefinitely), as well as labels not including the `run-id=${{github.run_id}}` specifier, and as such some jobs were stealing the new runners.
