### ISSUE TITLE
GitHub Actions Runner benchmark tables are empty

### ISSUE THREAD

**Issue by huonw** [runs-on/runs-on#104]
Hello!

The tables in https://runs-on.com/benchmarks/github-actions-runners/ currently seem to be empty, with only a header and no data rows (in Safari, Chrome and Firefox). Is this expected?

![image](https://github.com/runs-on/runs-on/assets/1203825/7340804c-9bf0-4ee9-9d32-5656bf769212)

As a comparison, the tables in https://runs-on.com/benchmarks/aws-ec2-instances/ still have content: 

![image](https://github.com/runs-on/runs-on/assets/1203825/cce9645d-f4da-4ba4-a837-d823461c2567)

(I'm not sure where I should be filing docs issues. Hopefully this is good enough 😄 )

**Comment by crohr** [comment]
Hi @huonw, thanks for raising the issue, it's now fixed!
