### ISSUE TITLE
Some jobs stuck in queue

### ISSUE THREAD

**Issue by shuluster** [runs-on/runs-on#106]
Version: 2.3.2

Some jobs stuck in queue. See attached log
[redacted-log-events-viewer-result.csv](https://github.com/user-attachments/files/16182485/redacted-log-events-viewer-result.csv)

Job label should be unique, including both run-id, job-name and matric chunk. 
`runs-on,runner=large,run-id=9896137128,matrix-chunk=0,job-name=run-black-box-test`

Log seems to stop right after `Successfully deleted message from the SQS queue`

There is no logs for the instance and there is no BidEvictedEvent event for this instance.

This happens one out of every few 10s of jobs we schedule and not on the same job or same matrix chunk.

**Comment by crohr** [comment]
Hello, is this issue recent? Can you see if the launched instance gets a Name assigned in the EC2 console, after some time?

can you also confirm that no other job is requesting a subset of the labels used for that workflow?

It’s late here but I will follow up tomorrow.

**Comment by shuluster** [comment]
Version of runs-on is 2.3.2 and issue is happening today.

Not exactly the same instance but it looks like the instance existed but did not have a name.
<img width="1413" alt="image" src="https://github.com/runs-on/runs-on/assets/1707910/e95addfa-099f-4492-8b44-f7a4c30927b4">

Checking the metrics it looked like it emitted one datapoint.

All labels are unique.

**Comment by crohr** [comment]
@shuluster could you send an email at cyril@runs-on.com so that we can schedule a call today to have a look at it together?

**Comment by shuluster** [comment]
Reached out.

Interestingly, I have been experimenting with different runner classes. Interestingly this issue only happened to me when I enable `m7` and it always happened on `m7i-flex.2xlarge`. Limiting the runner class to `c6,c7,m6` has since stopped this issue for the past 12 hours but the sample size might be too small. I do not fully understand what does `m7i-flex` do, especially the flex part.

**Comment by crohr** [comment]
@shuluster thanks, I'll book something in your calendar.

Regarding m7i-flex:

> [M7i-Flex instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/general-purpose-instances.html#general-purpose-hardware) ensure a baseline of 40% CPU performance while having the ability to scale up to full CPU performance for 95% of the time throughout a 24-hour window. Note that instances [consistently above the CPU](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/general-purpose-instances.html#general-purpose-hardware) for long periods could see a gradual reduction in “maximum burst CPU throughput.”

- https://www.vantage.sh/blog/m7i-flex-vs-t-series-cost

As you say I think it's more a sample size issue than something to attribute to the flex nature. If it reproduces, could you also share the tags that were added to the instance? Also note that `BidEvictedEvent` events in CloudTrail are delayed by ~15min.

**Comment by crohr** [comment]
After talking with @shuluster, the underlying reason appeared to be an internal error from EC2, as well as some quota issues. I'm going to close this for now, but feel free to reopen and/or comment with any reply you got from AWS regarding the internal error.

**Comment by shuluster** [comment]
Following up. After requesting the quota increase for 
1. total EC2 instances
2. RunInstances API
The issue seems to have stablize for the most part.

We do still occasionally see a job getting stuck in queue, without corresponding cloudtrail failures. I suspect this is underlying AWS ec2 launching not reliable. 

Happy to open another issue, is there a way to add "retries" for launching EC2 instances? If an EC2 instance does not become healthy within say a timeout, another Ec2 instance is launched.
