### ISSUE TITLE
Missing Java versions?

### ISSUE THREAD

**Issue by GauntletWizard** [runs-on/runs-on#111]
We're trying out runs-on, here's a log from our first attempt at a run. The diff we made was:

```
-    runs-on: ubuntu-latest
+    runs-on: [runs-on,runner=2cpu-linux-x64,"run-id=${{ github.run_id }}"]
```

And the failure we got was:
```

  ./gradlew ktlintCheck
  ./gradlew test
  ./gradlew build


FAILURE: Build failed with an exception.


* What went wrong:
A problem occurred configuring root project 'platform'.
> Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
   > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=17, vendor=any, implementation=vendor-specific} for LINUX on x86_64.
      > No locally installed toolchains match and toolchain download repositories have not been configured.
```

Per the [actions/runner-images](https://github.com/actions/runner-images/blob/ubuntu22/20240526.1/images/ubuntu/Ubuntu2404-Readme.md#java) repo, I would expect Java 17 to be installed and default on our runners.

**Comment by crohr** [comment]
@GauntletWizard hello, yes [only the default Java version](https://github.com/runs-on/runner-images-for-aws/blob/daa17ba3b63901f6c1512726137b4cba4f5a66cd/releases/ubuntu22/x64/images/ubuntu/toolsets/toolset-2204.json#L55-L59) (as per GitHub choosing) is installed on RunsOn images. This is to avoid making the images too big and slower to boot.

The recommendation is to use the [setup-java action](https://github.com/actions/setup-java) anyway, as more recent upstream images (ubuntu24) are going to be significantly slimmed down by GitHub, especially when an official action is supported for your language.
