### ISSUE TITLE
Enterprise runner

### ISSUE THREAD

**Issue by vafanassieff** [runs-on/runs-on#113]
Hey,

Will it be possible to use `runs-on` within an enterprise ?

Best

**Comment by crohr** [comment]
Hello, what do you mean by enterprise? For multiple orgs, you will need one license per organization. But you can send me an email at cyril@runs-on.com with more details so that I can give a better answer.

**Comment by vafanassieff** [comment]
> Hello, what do you mean by enterprise? For multiple orgs, you will need one license per organization. But you can send me an email at [cyril@runs-on.com](mailto:cyril@runs-on.com) with more details so that I can give a better answer.

It was not clear for me that billing was per org, make sense.

Thanks !
