### ISSUE TITLE
GitHub app install fails with "This app is configured for an incorrect organization. For security reasons it cannot be used. Please delete it and reinstall."

### ISSUE THREAD

**Issue by seanknox** [runs-on/runs-on#118]
> This app is configured for an incorrect organization. For security reasons it cannot be used. Please delete it and reinstall.

Hi, I got this when trying to install the app via CloudFormation. The org name was/is correct. We do have a GitHub enterprise name that is the same name as the organization.

**Comment by crohr** [comment]
Hello, could you send me a screenshot of your CloudFormation parameters (cyril@runs-on.com) that includes the organization field?

**Comment by seanknox** [comment]
The issue was our organization name was camelcase, and the CloudFormation parameters cared about that (OpenPhone vs openphone). Thanks for your help!
