### ISSUE TITLE
Custom tags for EC2 instance

### ISSUE THREAD

**Issue by piurafunk** [runs-on/runs-on#119]
I would like to revisit the custom tags idea from #67 . Where I work, our AWS resources are grouped by a tag for billing purposes. The tag key is already an established tag key, and our reports group them up nicely. We've used the AWS CDK to deploy the cloud formation template, which allowed us to add the tag to all of the resources that template specifies, and those show up correctly in our reports grouped together.

However, the instances that are launched aren't grouped with them, because they aren't launched with the tag. It would be very beneficial if we could customize those tags. By using the CDK, we can customize the resources that are imported from the template. If there were a resource there that we can override to set the specific tag, we could just use that.

In the end, if the instances can't have our specific tag on them, we'll have to manually add them to the reports after they've generated, to get them out of "uncategorized".

**Comment by crohr** [comment]
@piurafunk would a single custom tag be enough? If so I could add another CF parameter for that.

**Comment by piurafunk** [comment]
That would work for our needs, but if there were a way to add an array of tags, that would probably ensure any other use cases are covered. I'm not certain that's very possible with CF parameters, though.
