### ISSUE TITLE
Runs-on with many AWS accounts

### ISSUE THREAD

**Issue by pdegeeter** [runs-on/runs-on#120]
Hello,  

Is it possible to configure Run-on on multiple AWS accounts? Today, I have a development, pre-production and production account. I would like to avoid triggering CI/CD every time, on all 3 environments.

**Comment by crohr** [comment]
Hello, next version will introduce support for specifying an `env` label, so that you can target multiple RunsOn installations. I will close this issue once it is available, most likely before the end of this month.
