### ISSUE TITLE
Stack name doesn't match what IAM role expects

### ISSUE THREAD

**Issue by piurafunk** [runs-on/runs-on#121]
The IAM role `RunsOn-RunsOnServiceRole-<hash>` has this entry:

```json
{
    "Condition": {
        "StringEquals": {
            "aws:ResourceTag/stack": "RunsOn"
        }
    },
    "Action": [
        "ec2:TerminateInstances"
    ],
    "Resource": "arn:aws:ec2:*:*:instance/*",
    "Effect": "Allow"
}
```

And checking [AWS docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html), `StringEquals` is case sensitive: `Exact matching, case sensitive`.

However, for a given instance that it created, I get the following error message when trying to terminate it:

```
operation error EC2: TerminateInstances, https response error StatusCode: 403, RequestID: 5716c5e3-3b60-4e6f-88ca-0e41c5d1f54d, api error UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::<account id>:assumed-role/RunsOn-RunsOnServiceRole-<hash>/<random> is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:us-west-2:<account id>:instance/i-0a48ee7cb2c1e3489 because no identity-based policy allows the ec2:TerminateInstances action. Encoded authorization failure message: <encoded message>
```

Checking the tags of that instance, it has `stack` = `runson`, which isn't strictly `RunsOn`.

I created the stack via the Node CDK, with the following:

```node
new class extends Stack {
    constructor(scope: Construct, id: string, props: RunsOnProps) {
        super(scope, id, props);

        Tags.of(this).add('billing_app', 'runs-on');

        const __filename = fileURLToPath(import.meta.url);
        const __dirname = path.dirname(__filename);
        new CfnInclude(this, 'ThirdPartyTemplate', {
            templateFile: path.resolve(__dirname, 'template.yaml'),
            parameters: props,
        })
    }
}(app, 'RunsOn', app.node.getContext('runs-on'))
```

The file `template.yaml` being fetched is your CloudFormation file. I'm not certain that importing the stack this way would make the tags different, but it's possible the stack is not interpreting `RunsOn` as my stack name (as specified on the last line) but instead is making it full lower case.

It should be noted, the instance does get terminated somewhere, because it does shut down. I can't find logs yet as to what's doing it, though.

---

A possible solution is to use `StringEqualsIgnoreCase` instead of `StringEquals`.

**Comment by crohr** [comment]
Hello!

> operation error EC2

Where do you see this error? In the AppRunner logs?

**Comment by piurafunk** [comment]
Yes, in the log group `/aws/apprunner/RunsOnService-<random>/<random>/application`.

**Comment by crohr** [comment]
@piurafunk I've checked my own stacks, and the tag is correct:

<img width="385" alt="image" src="https://github.com/user-attachments/assets/fcc3edb8-64cb-4513-a0ae-bff8571c5584">

In CloudFormation, my stack is named `runs-on`. Can you confirm how yours is called? I'm not familiar enough with CDK to understand where the issues comes from.
