### ISSUE TITLE
Custom runner tags are overtly sanitized

### ISSUE THREAD

**Issue by shuluster** [runs-on/runs-on#125]
Version: 2.5.0
Configuration in CloudFormation for runner tags:

```
VantaOwner=shu@loop.com,VantaNonProd=true,VantaNoAlert=used_for_test,VantaContainsUserData=false,VantaContainsEPHI=false
```

Tags on actual EC2 instance:

```
vantanoalert: used-for-test
vantanonprod: true
vantacontainsephi: false
vantacontainsuserdata:false
vantaowner:shu-loop-com
```

Expected behavior: configure tags on instances exactly same it is configured as long as they are within AWS tags restrictions.

PS: I was able to achieve the expected behavior  before runs-on supported custom tags by adding tags to the Launch Template generated by runs-on. That seems be an easy solution.

**Comment by crohr** [comment]
Ah right I might be too aggressive with the sanitization. Will make a fix in next version, thanks for reporting.

**Comment by mooseracerPT** [comment]
My org has long ugly tag names full of `:`s, which are getting replaced by `-`s and breaking some reporting. Not a big deal but if you could let them survive intact it would help! Love the project so far, massive timesaver.
