### ISSUE TITLE
Unable to get SSM to work

### ISSUE THREAD

**Issue by jonwest** [runs-on/runs-on#129]
Is there some kind of configuration which is forcing SSM to be disabled on runners?  Rather than use SSH, we'd like to use Session Manager to be able to troubleshoot running workflows, but we're unable to get it to connect.

We've tried reinstalling the SSM snap, manually enabling it in the preinstall script, double-triple checking permissions, and using a custom AMI, but regardless of what we're trying, with RunsOn provisioned instances SSM _will not_ work.

We've tried creating an EC2 instance manually using the custom IAM role for RunsOn, and that works without issue.

**Comment by crohr** [comment]
SSM support is on my todo list, so I’ll have a look at this shortly

**Comment by jonwest** [comment]
In our testing, we were using Ubuntu AMI - `ami-0e86e20dae9224db8` in `us-east-1`. 
 - Spinup independently of runson with no changes in AWS in same VPC subnet for runs-on - session manager works.
 - Spinup using same AMI as a custom image in runs-on - session manager does not work.

This leads us to believe there is something about the runson agent/scripts that are causing the ssm agent/session manager to stop working.

**Comment by crohr** [comment]
> We've tried creating an EC2 instance manually using the custom IAM role for RunsOn, and that works without issue.

@jonwest could you share the custom IAM role you've used for that?
