### ISSUE TITLE
List of permissions needed for custom IAM role?

### ISSUE THREAD

**Issue by rathpc** [runs-on/runs-on#13]
Do you have a list somewhere of the least required permissions an IAM user would need if we want to create a new one to be used rather than assuming the role of the user creating the stack?

I would rather create a new IAM role for this specific purpose but need to know everything it should have access to. Thanks!

**Comment by crohr** [comment]
@rathpc extended IAM permissions are only required to create the cloudformation stack. The stack will then create a new role that will be used by the RunsOn service, with a restricted set of permissions that you can see [here](https://github.com/runs-on/runs-on/blob/main/cloudformation/template.yaml#L256-L304).

Does that answer your question? Or do you want to create a new IAM user just for executing the CloudFormation stack creation/updates?

**Comment by rathpc** [comment]
I am referring to this section of the template
![image](https://github.com/runs-on/runs-on/assets/5623579/dae9a9cf-684e-4894-9358-7af1695a74cc)

But I believe you answered my question that when the service does anything it is using a new limited permission role rather than the one used to create the stack. Is that correct?

**Comment by crohr** [comment]
Yes exactly!
