### ISSUE TITLE
Spurious networking errors

### ISSUE THREAD

**Issue by marqueurs404** [runs-on/runs-on#130]
Hi @crohr, first and foremost just wanna say thanks for creating this awesome project! It's my first day trying this out and I'm pretty impressed by how easy it is to get working (mostly) in under an hour.

However, I have noticed spurious networking errors occurring in some of our jobs quite consistently. Not sure if it's because of the highly parallel nature of our workflow that's pushing some network/os limits, yet such issues are very rare with the default github runners.  Wondering if you have any idea what may cause this?

We are using the default cloudformation stack values, and our jobs are running on one of these two configs:
- `runs-on: [runs-on,runner=2cpu-linux-x64,"run-id=${{ github.run_id }}"]` 
- `runs-on: [runs-on,runner=4cpu-linux-x64,"run-id=${{ github.run_id }}"]`

Some error logs coming from our python tests:

![image](https://github.com/user-attachments/assets/d945d638-7dbb-465a-a444-311bf76e2a65)
![image](https://github.com/user-attachments/assets/8d4f456e-505c-4795-a0c3-7c06e715dd07)

**Comment by crohr** [comment]
Hi @marqueurs404, could you tell a bit more about your configuration: region, private mode or not?

That's the first time I see this kind of feedback (and many thousands of runners are launched every hour), so I suspect it is specific to your workflow. Can you tell more about what hosts it is trying to reach?
