### ISSUE TITLE
[Feature Request] Option to suppress the list of admins / default admins from runner output.

### ISSUE THREAD

**Issue by colstrom** [runs-on/runs-on#138]
Currently, runners output a list of `DefaultAdmins` and `Admins` to their logs. This is helpful for troubleshooting but has side-effect of exposing this information to anyone who can read the logs, which in the case of public workflows, may be a broader audience than some users would prefer (or intend).

Can we get an option to disable or suppress this output **at the deployment level** specifically? I suspect that the ideal **default** should be to have it disabled, and to require an explicit opt-in to enable it, with a clear warning that this information will be in logs. An additional control to determine whether or not this can be overridden by repo-level configuration would also be useful, as some users may want to enforce this strictly, and others may not.

Please and thank you. <3

**Comment by crohr** [comment]
Instead of adding another CF parameter, what about always disabling it for public projects (and only display the admins and default admins **count** just to have a rough idea of how many people are supposed to be able to SSH into the runner) and keep it always visible for private projects?

**Comment by colstrom** [comment]
Anonymizing the data by only including a count would limit the information exposed, so that's definitely an improvement. It might also be worth noting that I have `AllowSSH` set to `false`, so I'm not sure if it makes sense to display **anything** in that particular case, but I could see a count being a reasonable tradeoff in other cases.

I think an option to disable it entirely is preferable, since even private repos can have external contributors that aren't privy to information about which users are admins within the broader org, and the logs expose that.

**Comment by crohr** [comment]
> It might also be worth noting that I have AllowSSH set to false, so I'm not sure if it makes sense to display anything

If `ssh=false`, then currently nothing is displayed in the job logs. Or are you talking about something else?

**Comment by colstrom** [comment]
To clarify, what I mean is that In my current CloudFormation parameters, `AllowSSH` is set to `false`, and the "Setup job" stage of a workflow in the corresponding org outputs the following:

```text
Machine name: 'ip-10-REDACTED'
Runner Instance
  |       INFO        |                           VALUE                           |
  |-------------------|-----------------------------------------------------------|
  | SSH               | ssh runner@10.REDACTED
  | DefaultAdmins     | [REDACTED REDACTED REDACTED
  |                   | REDACTED REDACTED]
  | Admins            | [REDACTED REDACTED REDACTED
  |                   | REDACTED REDACTED REDACTED
  |                   | REDACTED REDACTED REDACTED REDACTED
  |                   | REDACTED REDACTED
  |                   | REDACTED REDACTED
  |                   | REDACTED]
  | Organization      | REDACTED
  | Region            | us-east-1
  | AvailabilityZone  | us-east-1a
  | Version           | v2.3.2
  | Runner            | runs-on--i-REDACTED--REDACTED
```

I've omitted the specifics for (probably) obvious reasons, but you can see from the above that the `Admins` list contains many more entries than the `DefaultAdmins` list defined in CloudFormation parameters, and those are GitHub admins.

If it's relevant, the `runs-on` label for that job was:

```yaml
runs-on: runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }},image=ubuntu22-full-x64,hdd=64
```

So no additional ssh-related parameters were defined at that level. It's also not using a custom image or runner definition that might enable SSH or something, just to rule that out.

**Comment by crohr** [comment]
@colstrom sorry to go back to this again :) but `AllowSSH` is not a valid CloudFormation parameter so I'm a bit confused. Did you make some changes to the template maybe?

Also I notice you are on v2.3.2, so I believe the hiding was introduced in a more recent release. Can you upgrade and see if this issue still needs to be open?
