### ISSUE TITLE
[Feature request] Add log group arns to output

### ISSUE THREAD

**Issue by hans-d** [runs-on/runs-on#147]
Would ike to see the arns of the created log groups in the stack output. That way we can pick them up and use if for subscribtions to our log system (we run the CF tempate in a TF wrapper)

**Comment by crohr** [comment]
@hans-d the only one I could output is the log group for ec2 instance logs. The two log groups for AppRunner are unfortunately entirely created and managed by AWS, and at this point we cannot easily access their ARN from CF.

**Comment by hans-d** [comment]
Thanks, seeing that it needs some trickery as well from the terraform side... But they arns have predictable formats, so I will try with that.
