### ISSUE TITLE
Cookies must be enabled to use GitHub.

### ISSUE THREAD

**Issue by muniter** [runs-on/runs-on#15]
Hi, I'm trying to setup runs-on the stack deploys ok, but when I go to the stack output url and press the "Register Github App" button I get an error from github that says: `Cookies must be enabled to use GitHub.`

I tried it with firefox and chrome same result.

![image](https://github.com/runs-on/runs-on/assets/9699804/27c2d300-7532-4a2d-8052-332ba9017596)

**Comment by crohr** [comment]
Hello, this looks weird. I'm not sure this is related to RunsOn specifically. Does GitHub work fine otherwise, in the same browser?

**Comment by crohr** [comment]
@muniter what did you input as the organisation name in the CloudFormation template? For instance if my org is at https://github.com/crohr, you must input `crohr`, not the full address.

**Comment by muniter** [comment]
> @muniter what did you input as the organisation name in the CloudFormation template? For instance if my org is at https://github.com/crohr, you must input `crohr`, not the full address.

That must be it, I pasted the full url. Thank you!

Will try again and report back.

**Comment by muniter** [comment]
Just tried again an it worked great, sorry for the confusion. It was clearly in the instructions.
