### ISSUE TITLE
When EBS default encryption is enabled using a custom KMS key, runs-on-RunsOnServiceRole lacks permissions

### ISSUE THREAD

**Issue by NickLavrov** [runs-on/runs-on#151]
Under the `AWS::EC2::LaunchTemplate` resource, under `BlockDeviceMappings.Ebs`, since `KmsKeyId` is not specified, when EBS encryption is enabled by default using a custom KMS key, `runs-on-RunsOnServiceRole` will fail to start EC2 instances since it will not have permissions to use the key for the volumes.

I can see 2 ways to fix it:
1. Specify `KmsKeyId` to use the default EBS key, maybe like `KmsKeyId: alias/aws/ebs`. This can even be a parameter.
2. Specify some option to attach an IAM policy to the `runs-on-RunsOnServiceRole` iam role that grants the required kms permissions to use the key. There could be a parameter for specifying the kms key arn, and if specified, attach a policy that grants permissions. Do note that this could run into issues since, if the user has a key policy on the key, they need to edit it to allow this IAM role to use it, and that fact would be managed outside of cloudformation.

Option 1 seems easier. Option 2 can be considered a more generalized version of option 1.

**Comment by NickLavrov** [comment]
https://github.com/runs-on/runs-on/pull/152

**Comment by crohr** [comment]
v2.5.7 is available with #152. Closing this for now.
