### ISSUE TITLE
pricing question

### ISSUE THREAD

**Issue by Fraccaman** [runs-on/runs-on#154]
I was looking at the docs, in particular [at this page](https://runs-on.com/pricing/). In the price table, there is a mention that the selected region is `us-east-1` that the cost includes`compute and storage` costs. I was wondering, which price are you considering for the compute part: on-demand, spot, etc...
Thanks!

**Comment by crohr** [comment]
Hello,

The prices displayed are for spot. You can view both on-demand and spot in the calculator tab.

Thanks,
Cyril

**Comment by Fraccaman** [comment]
Ahhh thanks for totally missed it! Ill close the issue :)
