### ISSUE TITLE
Jobs getting stuck due to GitHub rate limiting refreshWorkflowRunStatus in v2.5.7

### ISSUE THREAD

**Issue by bruno-chavez** [runs-on/runs-on#156]
Hi, I upgraded to `v2.5.7` yesterday and about an hour ago, started to get all my jobs queued due to GitHub rate limiting the API `refreshWorkflowRunStatus`.  I initially upgraded from `v2.5.4` because I was getting the delete runner API rate limited, but seems upgrading only moved the issue from one API to another. Any stable version I can downgrade until this issue gets fixed for good?

Here are the relevant logs:

```
{
    "level": "info",
    "app_environment": "production",
    "app_stack_name": "runs-on",
    "app_version": "v2.5.7",
    "labels": [
        "runs-on",
        "runner=1cpu-linux-x64",
        "run-id=11574316123"
    ],
    "status": "queued",
    "run_id": 11574316123,
    "deployment_id": 0,
    "job_id": 32221177367,
    "job_url": "REDACTED",
    "job_name": "CI / Validate",
    "time": "2024-10-29T13:45:40Z",
    "message": "Calling GitHub API (refreshWorkflowRunStatus)"
}
```

```
{
    "level": "error",
    "app_environment": "production",
    "app_stack_name": "runs-on",
    "app_version": "v2.5.7",
    "labels": [
        "runs-on",
        "runner=1cpu-linux-x64",
        "run-id=11574316123"
    ],
    "status": "queued",
    "run_id": 11574316123,
    "deployment_id": 0,
    "job_id": 32221177367,
    "job_url": "REDACTED",
    "job_name": "CI / Validate",
    "error": "rate: Wait(n=1) would exceed context deadline",
    "time": "2024-10-29T13:45:40Z",
    "message": "Error waiting for GitHub rate-limiter to proceed"
}
```

```
{
    "level": "error",
    "app_environment": "production",
    "app_stack_name": "runs-on",
    "app_version": "v2.5.7",
    "labels": [
        "runs-on",
        "runner=1cpu-linux-x64",
        "run-id=11574316123"
    ],
    "status": "queued",
    "run_id": 11574316123,
    "deployment_id": 0,
    "job_id": 32221177367,
    "job_url": "REDACTED",
    "job_name": "CI / Validate",
    "error": "rate: Wait(n=1) would exceed context deadline",
    "time": "2024-10-29T13:45:40Z",
    "message": "Failed to fetch workflow run status"
}
```

```
{
    "level": "error",
    "app_environment": "production",
    "app_stack_name": "runs-on",
    "app_version": "v2.5.7",
    "labels": [
        "runs-on",
        "runner=1cpu-linux-x64",
        "run-id=11574316123"
    ],
    "status": "queued",
    "run_id": 11574316123,
    "deployment_id": 0,
    "job_id": 32221177367,
    "job_url": "REDACTED",
    "job_name": "CI / Validate",
    "error": "rate: Wait(n=1) would exceed context deadline",
    "time": "2024-10-29T13:45:40Z",
    "message": "❌ Unable to schedule runner. Will be retried if possible."
}
```

**Comment by crohr** [comment]
I believe you were already rate-limited or close to the limit before you performed the migration, and so v2.5.7 inherited it. The issue is that GitHub rate-limits over a sliding window of 1h, instead of regularly giving back tokens every second. So if you had exhausted all your credits, no job can run until the 1h window expires.

I believe v2.5.7 should work fine once you get your credits back. Depending on your load and rate-limit issues, you could also use the Environments feature of RunsOn to use multiple GitHub Apps, so that you can combine the rate-limits for each app (each app gets its own rate-limit).

You can follow the token situation by grepping for "Current tokens" in the AppRunner logs. Would be interesting to know what is your GitHub rate-limit.

**Comment by crohr** [comment]
@bruno-chavez hello, a regression has indeed been found in v2.5.7, please upgrade to v2.5.8. Sorry for the inconvenience!

**Comment by bruno-chavez** [comment]
Hi! Thank you for reporting back, will stay in `v2.3.2` for a week or two in order to test if any rate limiting issues happens in that version as well. After that we will make sure to update to the latest version!
