### ISSUE TITLE
self hosted runner version

### ISSUE THREAD

**Issue by filintod** [runs-on/runs-on#157]
I'm seeing some messages after a failure in a workflow:
```
This job failure may be caused by using an out of date self-hosted runner. 
You are currently using runner version 2.319.1. Please update to the latest version 2.320.0
```

and was wondering if the latest version of runs-on has it as I did not see any reference on the release notes.  Thanks

**Comment by crohr** [comment]
@filintod Base images were a bit outdated because I didn't approve the deployment of new images last week. A new job is running now, which should publish updated images momentarily (https://github.com/runs-on/runner-images-for-aws/actions/runs/11608203458/job/32324471407)

**Comment by crohr** [comment]
And just to make it clear: image lifecycle is not dependent on new RunsOn releases because it does indeed need more regular updates.
