### ISSUE TITLE
Support for ca-central-1

### ISSUE THREAD

**Issue by bartdag** [runs-on/runs-on#17]
Would it be possible to add support for ca-central-1? I believe m7a and c7a instances are not available in this region yet, but m7i and c7i are.

We would like to evaluate runs-on, but we have to use a region in Canada for legal reasons. 

Thanks!

**Comment by crohr** [comment]
@bartdag Hello, unfortunately AppRunner, which is required by RunsOn, is not available in ca-central-1

<img width="837" alt="image" src="https://github.com/runs-on/runs-on/assets/6114/539f0d90-675d-43dc-80f7-43c52aac8b05">

Is there any region from the supported list that would work for you?

**Comment by crohr** [comment]
Please let me know if we can close the issue, or if you'd like an additional region supported. Thanks!

**Comment by bartdag** [comment]
@crohr apologies for the delay, especially since you responded so quickly. I'll open another ticket if we need another region. Thanks for the explanation about AppRunner, we'll monitor this service if it ever appears in ca-central-1.
