### ISSUE TITLE
Read license key from Secrets Manager / AWS SSM

### ISSUE THREAD

**Issue by p5** [runs-on/runs-on#176]
Many of us define almost all the resources deployed to our account as IaC.  
Currently runs-on requires the license key to be defined in CloudFormation plaintext parameters, meaning we cannot (easily) define the stack as Terraform.  We either need to have additional external infrastructure available (e.g. Vault) or to wrap the infrastructure with custom logic to extract values from SSM ourselves.

It would be great if we could enter a license key SSM path or secrets manager name so we can define the stack safely in our infrastructure configuration.

**Comment by crohr** [comment]
@p5 this makes sense, I'll see how I can best do this while retaining enough simplicity when using CloudFormation directly.
