### ISSUE TITLE
AppRunner Log paths output in cloudformation stack

### ISSUE THREAD

**Issue by 7adamf** [runs-on/runs-on#184]
Please can you add the cloudwatch log groups from App Runner as outputs in the Cloudformation Stack so we can have monitoring tools find those locations.

**Comment by crohr** [comment]
@7adamf unfortunately this is not something that AWS exposes. The best you can do is to output the AppRunner ARN, which can then be used to build the CloudWatch paths:

Example ARN:
```
arn:aws:apprunner:us-east-1:756351362063:service/RunsOnService-NWAiVjCasSdH/5eaf2c1bd7ab4baaacfde8b7dd574fda
```

Application logs path: 
```
/aws/apprunner/RunsOnService-NWAiVjCasSdH/5eaf2c1bd7ab4baaacfde8b7dd574fda/application
```

I.e. remove the prefix `arn:aws:apprunner:us-east-1:756351362063:service/` from the ARN, and then you can build the CloudWatch path.
