### ISSUE TITLE
Environments in custom images

### ISSUE THREAD

**Issue by 7adamf** [runs-on/runs-on#185]
Hey there, I have tried this and don't seem to be able to get it to work. Is it possible to have the custom image definitions in .github-private respect the env variable? This would allow us to control which runners run where. Thanks.

Example:

my_custom_image:
    env: my_env   <-- could this be enabled?
    family: ["m7i-flex", "m7a", "m7i"]
    image: my_custom_image
    ssh: false
    spot: false
    cpu: 2
    ram: 2
    hdd: 20

**Comment by crohr** [comment]
Hi @7adamf, unfortunately this is not possible, because RunsOn installations must be able to quickly decide whether they need to process an incoming workflow job, based just on the webhook payload.
