### ISSUE TITLE
Snooze cost allocation tag alert if cost reports are non-zero

### ISSUE THREAD

**Issue by skyeagle** [runs-on/runs-on#187]
Hi there,

Thanks for the great work on this service!

We keep receiving "Unable to register cost allocation tag" alert while the tag is active in the root account, and cost reports get generated on a daily basis. There might be a bug on this alert. Any help would be appreciated, thank you!

**Comment by atkeson** [comment]
We are running into this. We get the email about cost allocation tags not being set up every 5-7ish days (seems a bit random). Our cost reports are non-zero

**Comment by skyeagle** [comment]
> We are running into this. We get the email about cost allocation tags not being set up every 5-7ish days (seems a bit random). Our cost reports are non-zero

Yep, that's is the case for us as well.
