### ISSUE TITLE
[Feature Request] Ability to add additional environment variables that can be used in runner steps in /opt/runs-on/pre.sh

### ISSUE THREAD

**Issue by ali-kafel** [runs-on/runs-on#188]
Hello,

Currently the `/opt/runs-on/pre.sh` script adds `RUNS_ON_*` environment variables that can be used in the later github actions workflow steps globally. I tried adding more environment variables using the preinstall script but those never persisted in the later steps in the workflow. It would be nice to have a way to add additional global github actions environment variables in the `pre.sh` script so we can use them in later steps.

Namely I am trying to add aws region environment variables in the runner setup.

**Comment by crohr** [comment]
Yes the preinstall is executed before the GitHub agent is launched. What kind of variables would you like to expose?

**Comment by ali-kafel** [comment]
> Yes the preinstall is executed before the GitHub agent is launched. What kind of variables would you like to expose?

I am trying to expose some AWS env vars:
```
    preinstall: |
      #!/bin/bash -ex
      cat /opt/runs-on/pre.sh
      cat /opt/runs-on/env
      RUNS_ON_ENV_FILE=/opt/runs-on/env
      bash /opt/runs-on/pre.sh
      echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
```

Some of the aws actions fail if you don't have the region env var set. In the Actions Runner Controller these were already set for you if you assumed an AWS role using an IRSA role:
```
runner@small-mjtcf-runner-hqn6h:/$ env | grep AWS
AWS_DEFAULT_REGION=us-east-1
AWS_REGION=us-east-1
AWS_ROLE_ARN=arn:aws:iam::9999999:role/runner-role
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_STS_REGIONAL_ENDPOINTS=regional
```

**Comment by crohr** [comment]
AWS_REGION is not automatically exported to avoid conflicts (but maybe it should be). Maybe you could use a job-level env setting instead?

```
env:
  AWS_REGION: ${{ env.RUNS_ON_AWS_REGION}}
```

**Comment by ali-kafel** [comment]
> AWS_REGION is not automatically exported to avoid conflicts (but maybe it should be). Maybe you could use a job-level env setting instead?
> 
> ```
> env:
>   AWS_REGION: ${{ env.RUNS_ON_AWS_REGION}}
> ```

That would indeed solve it but we would have to set that explicitly for every workflow we have across hundreds of repos. Ideally we won't want these env vars for us everywhere.

**Comment by crohr** [comment]
Ok I see. I will add a way to do it.
