### ISSUE TITLE
Runner selection with job labels

### ISSUE THREAD

**Issue by joh-klein** [runs-on/runs-on#199]
I'm trying to wrap my head around runner selection. I have some jobs that I would like to define like this:
```
runs-on:
- runs-on=${{ github.run_id }}
- cpu=2+16
- ram=2+32
- spot=lowest-price
```
Basically what I want is the cheapest spot instance with at least 2vCPU and 2GB of RAM. Either arm64 or x64 is fine. Family and generation doesn’t matter either – like I said, it's supposed to be as cheap as possible.

It looks like that is not possible. Or not in the way I’m trying to do it. (I’m getting "Invalid runner spec" back from AWS)

**Comment by joh-klein** [comment]
Thanks for your answer. Two follow ups:
- would you consider changing the `family` and `image` requirement?
- why do you say the older instance types are not worth it? Are they significantly slower?

**Comment by joh-klein** [comment]
Thanks for the explanation! Maybe you already wrote this on the website and I didn't read it – but if not it would be great if you could add that part about image and family.

Would it make sense to have something similar to the cpu selection (min+max) with `family`? A shorthand for "I want at least c/m/r-gen6-family, but don't mind if it is gen7 or gen8"? Right now I would have to write `family=c6+c7+c8+m6+m7+m8+r6+r7+r8`

**Comment by crohr** [comment]
I have updated a bit the documentation. For now I think it's better to be explicit about family types, even if that means setting a somewhat large `family` array. I think with custom runner definitions this is manageable.
