### ISSUE TITLE
is there a way to store github actions in S3

### ISSUE THREAD

**Issue by filintod** [runs-on/runs-on#202]
Trying to reduce nat gateway costs and the most traffic (after checking in cloudwatch) seems to be related to github. I know we sometimes have a large amount of logs in our runs and I'm suspecting that as an issue and was wondering if storing these in S3 is an option

**Comment by crohr** [comment]
What was the issue in the end?

**Comment by filintod** [comment]
@crohr still figuring it out, I thought the majority of the data bytes was pushing to github, but the majority is pulling from it so still trying to figure it out.
