### ISSUE TITLE
Terminated runners not being removed from repo

### ISSUE THREAD

**Issue by techied** [runs-on/runs-on#204]
Hi,

I just installed runs-on yesterday and it seems to be working well, except that my repository runners list is now full of all of these runners that no longer exist (about 40 or so):

Is this working as expected?

<img width="851" alt="image" src="https://github.com/user-attachments/assets/5028e299-9fd5-41ac-b11c-defb7eafa010" />

**Comment by crohr** [comment]
They should be unregistered, unless you are running out GitHub API credits. They will get unregistered after 24h by GitHub automatically anyway so no big deal. How many jobs did you launch over the last 24h?

**Comment by techied** [comment]
> They will get unregistered after 24h by GitHub automatically

ahh, didn't know that! We have had about 100 jobs in the last 24h but only added runs-on about 18h ago
