### ISSUE TITLE
"Job retries and housekeeping" docs may have outdated reference to spot interruptions not being retried

### ISSUE THREAD

**Issue by huonw** [runs-on/runs-on#206]
I was reviewing https://runs-on.com/monitoring/housekeeping/  and noticed (emphasis mine):

> detect spot interruptions, so that the job is properly shut down and the GitHub UI is updated. *Currently, that job is not automatically re-tried*.

Which seems to be in conflict with:

- later in that page: [NB. unrelated typo: should "Those errors" here be "These errors" (o -> e)?]
  > Those errors will be detected after launching an instance, and will trigger a new instance launch:
  > ...
  > - Server.SpotInstanceTermination : The instance was terminated because the number of Spot requests with a maximum price equal to or higher than the Spot price exceeded available capacity or because of an increase in the Spot price.
- the `retry=when-interrupted` label: https://runs-on.com/configuration/job-labels/#retry
  > retry=when-interrupted: default for spot instances. Will retry at most once the interrupted job, using an on-demand instance.
- the 2.6.0 changelog: https://runs-on.com/changelog/#v260
  > Auto-retry mechanism for spot interruptions

Thus, I suspect that original piece of text is either out-of-date (or, if not, is misleading and could be improved)!

(Thanks for RunsOn!)

**Comment by crohr** [comment]
@huonw thanks, I have updated the documentation!
