### ISSUE TITLE
AppEc2QueueSize Usage

### ISSUE THREAD

**Issue by ri-roee** [runs-on/runs-on#31]
Hello there!

Is `AppEc2QueueSize` actually used anywhere? From a quick [repo scan](https://github.com/search?q=repo%3Aruns-on%2Fruns-on%20AppEc2QueueSize&type=code) it looks like its only ever referenced in the CF stack. I also can't find any AWS Quota that matches that restriction. Thanks!

**Comment by crohr** [comment]
It is used as RUNS_ON_EC2_QUEUE_SIZE in the code, and serves as the queue size for rate limiting RunInstances API calls

**Comment by ri-roee** [comment]
Gotcha, and do you generally recommend we ask AWS to increase this param? In other words is the default limit of 2 a bottleneck for most cases?

**Comment by crohr** [comment]
Really depends on your max number of concurrent jobs. If you need to launch more than 10-20 runners at a time, it would be best to ask for an increase yes, otherwise the delay will start to be noticeable. 

For many use cases the default is fine though.

**Comment by ri-roee** [comment]
Ah I'm seeing this now: https://docs.aws.amazon.com/ec2/latest/devguide/ec2-api-throttling.html#throttling-increase

I wonder if there's some log or metric we can monitor to see if we're hitting that rate limit threshold often?
