### ISSUE TITLE
Support for launching instances in multiple AZs

### ISSUE THREAD

**Issue by vlj91** [runs-on/runs-on#32]
At present we can only launch instances in a single AZ. It would be nice to be able to launch instances in multiple AZs, in particular to avoid instance types being unavailable.

Quite often, us-east-1a will run out of instance types in the preconfigured classes (e.g `4cpu-linux`).

**Comment by crohr** [comment]
Can you confirm you are on the latest version (v1.7.3)? m7i family has been added in addition to m7a, which should help.

You could also add other family like c6a which are often available. 

I am looking at expanding to more AZs, but for now adding more family types is best.

**Comment by vlj91** [comment]
Ah, we were on 1.7.2, have upgraded to 1.7.3 and will see how that goes. Thanks @crohr
