### ISSUE TITLE
Runner Name Duplication Error

### ISSUE THREAD

**Issue by ri-roee** [runs-on/runs-on#33]
Hey there 👋🏼 

We're seeing this intermittent error, wondering if you know about it/have a workaround?: 
```
HttpError: Already exists - A runner with the name *** already exists.
```

**Comment by crohr** [comment]
Yes! Occurs when GitHub API is misbehaving. Will be fixed when I release this fix https://github.com/runs-on/runs-on/pull/30. Most likely tomorrow!

**Comment by ri-roee** [comment]
Sweet, thank you so much @crohr!
