### ISSUE TITLE
Sidecar support

### ISSUE THREAD

**Issue by mjclarke94** [runs-on/runs-on#34]
It would be great to add the ability to run sidecar containers alongside the runner. One example use case might be spinning up a lightweight bazel-remote-cache server as the runner instance starts up, meaning that you are only running servers supporting CI tasks when they are needed.

**Comment by crohr** [comment]
@mjclarke94 wouldn't it be possible to just set it up as the first step of the workflow?

**Comment by crohr** [comment]
@mjclarke94 in case you have more insight to give me here, let me know :)
