### ISSUE TITLE
Implement Support for Multiple Runners per EC2 Instance

### ISSUE THREAD

**Issue by theophileds** [runs-on/runs-on#35]
Hey there,

It might be interesting if we could set multiple runners per instance. Because with AWS there is often a shortage of instances, especially the m7a type. We're still sticking with ARC because we can run multiple jobs in one instance, which provides more garantee in case of shotage.

**Comment by crohr** [comment]
@theophileds hello, RunsOn automatically handles this case, just add multiple family types to your runs-on definition, and it will pick the one that is available at the time of launching.

v1.7.3 also introduced m7i-flex as a default instance type, which is more widely available everywhere, and less subject to interruptions.

See https://runs-on.com/reference/benchmarks-ec2-instances/, which I've just released.

**Comment by crohr** [comment]
See https://runs-on.com/features/custom-runners/ for how to define the `family` label, either inline in the `runs-on: ` definition, or via config file.

**Comment by theophileds** [comment]
That's great!

Thanks.

**Comment by crohr** [comment]
@theophileds can I close? If you'd like some more details, just send me an email at cyril@runs-on.com

Thanks!
