### ISSUE TITLE
Spot-Instance Termination Monitoring

### ISSUE THREAD

**Issue by ri-roee** [runs-on/runs-on#36]
Hey @crohr!

We're running into an issue where on rare occasions spot instances are terminated (expected) however github workflows never register this event and thus continue to run until they hit the built-in timeout. I was wondering whether you had a roadmap item to include spot-instance termination monitoring, maybe via [EventBridge](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-instance-termination-notices.html), that would poll for terminations and if found would cancel the existing workflow and re-schedule it onto another node. Unfortunately because of the high SLA we have for internal CI this bug is going to force us to switch to on-demand instances until we can guarantee high-availability.

**Comment by ri-roee** [comment]
To add some color here - the active job continues to run while github does call the overall workflow a failure.

I thought that maybe using `persistent` spot instances might get us out of this pickle since the spot request will re-open upon termination but I think the same issue would exist with Github not registering the dropped node and thus not restarting the job as desired. Due to this, I still think that handling this logic in the controller with some reconciliation loop is the right move forward.

**Comment by crohr** [comment]
Hi, this looks like an interesting idea. The issue I see is that maybe some workflows have side effects and thus auto-restarting them might be problematic (like deploy jobs etc).

Could you tell me a bit more about your jobs: what is their average duration? And the current instance type used?

For now I think your best bet is to avoid instances with high interruption percentage. I've published a benchmark here that can help you choose the correct instance type: [https://runs-on.com/reference/benchmarks-ec2-instances/](https://runs-on.com/reference/benchmarks-ec2-instances/). Have you tried m7i family?

**Comment by ri-roee** [comment]
Fixed in #38! Thanks again @crohr
