### ISSUE TITLE
S3  Docker Build Cache Authentication Issue

### ISSUE THREAD

**Issue by ri-roee** [runs-on/runs-on#37]
Hey @crohr,

I was testing out the new docker build s3 cache and am running into an authentication issue with AWS (403 forbidden to be exact). How are credentials passed along? Seems that it can be set using the standard SDK [auth](https://docs.docker.com/build/cache/backends/s3/#authentication). Thanks!

**Comment by crohr** [comment]
This can happen if you set aws credentials in your workflow, as env variables instead of using the official AWS action. Can you share your workflow YAML maybe?

**Comment by ri-roee** [comment]
I think you're right, setting the AWS_ACCESS_KEY in a previous job threw off the authentication. Thank you for the quick response!
