### ISSUE TITLE
Unable to register cost allocation tag for `stack` tag key

### ISSUE THREAD

**Issue by alecmocatta** [runs-on/runs-on#4]
Just trying this out and received this error email. Maybe related, the "costs and troubleshooting" issue also hasn't been created.

```text
Hello, here are the last 1 errors for RunsOn:

❌ Unable to register cost allocation tag for `stack` tag key.

This is expected if you are running RunsOn in an AWS sub-account.

However, for cost reports to work, you will have to manually enable cost allocation tags in the parent account for the `stack` tag key.

See https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/activating-tags.html for more information.
```

At [Billing and Cost Management -> Cost Allocation Tags -> User-defined cost allocation tags](https://us-east-1.console.aws.amazon.com/billing/home?region=us-east-1#/tags) there isn't a tag called `stack`. I presume there's some delay between such a tag being created and it appearing here? And that delay is presumably the source of the above error, rather than being in an AWS sub-account as I in fact ran in the root account.

<details><summary>I did receive a costs email, right before the error email:</summary>

```text
Hello, please find below the daily costs for the `stack:ci-runs-on` stack.

## Daily costs

| Date       | Cost       |
|------------|------------|
| 2024-01-02 | 0.00 |
| 2024-01-03 | 0.00 |
| 2024-01-04 | 0.00 |
| 2024-01-05 | 0.00 |
| 2024-01-06 | 0.00 |
| 2024-01-07 | 0.00 |
| 2024-01-08 | 0.00 |
| 2024-01-09 | 0.00 |
| 2024-01-10 | 0.00 |
| 2024-01-11 | 0.00 |
| 2024-01-12 | 0.00 |
| 2024-01-13 | 0.00 |
| 2024-01-14 | 0.00 |
| 2024-01-15 | 0.00 |
| 2024-01-16 | 0.00 |

Note: costs are fetched from the AWS Cost Explorer API and may be delayed by up to 24 hours. Costs are for the whole organization, and they are displayed only if you the Cost Allocation Tag for `stack:ci-runs-on` has been enabled in your AWS account. Once enabled, you can also filters costs for this tag using the Cost Explorer AWS UI.

See https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/activating-tags.html for more information.
```

</details>

**Comment by crohr** [comment]
Hi @alecmocatta,

The "costs and troubleshooting" issue is no longer created, hence why you're receiving emails instead. I think the README no longer mentions an issue being created. An issue was not a good way to show costs and errors in case of a public repository.

As for the allocation tag, can you confirm whether you installed the stack in your main AWS account, or in a sub-account?

**Comment by alecmocatta** [comment]
I was in the main AWS account. After 12 hours or so `stack` appeared on the aforementioned page and I manually enabled it. Expected behaviour per [AWS's docs](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/activating-tags.html):

> After you create and apply user-defined tags to your resources, it can take up to 24 hours for the tag keys to appear on your cost allocation tags page for activation. It can then take up to 24 hours for tag keys to activate.

And re the "costs and troubleshooting" issue, agreed, was just following the demo video and hadn't realised that had changed.

**Comment by crohr** [comment]
@alecmocatta Thanks, I will change the code so that the allocation tag activation is only triggered at least 24h after the first install. This should make the error disappear.
