### ISSUE TITLE
Terminate ec2 instance when job is canceled

### ISSUE THREAD

**Issue by tropictim** [runs-on/runs-on#44]
It looks like when a workflow job is canceled, the EC2 instance continues to run. Would runs-on be able to support terminating the EC2 instance for a canceled job?

**Comment by crohr** [comment]
It should already terminate the instance (20s after the runner agent exits). Which version are you using?

**Comment by tropictim** [comment]
I'm on 1.7.4. I just ran another test and noticed that 17/20 instances for the canceled workflow terminated but 3 were left running. It seems to happen when the workflow is canceled before the runner picks up the job. If the workflow is canceled after all 20 jobs are picked up, all of the instances terminate.

**Comment by tropictim** [comment]
Could the `runs-on-workflow-job-id` tag be used to link the runner to the job? Looks like that tag is on the instance and in the `workflow_job` webhook event

**Comment by crohr** [comment]
Theoretically yes, but in practice you cannot be sure which job will be executed on the spawned runner: in case you have multiple jobs with the same labels launched at the same time, each one can execute any of the jobs matching the labels. There is no way to make that deterministic unfortunately.

Which means RunsOn could kill a runner that is actually running a proper job.

**Comment by tropictim** [comment]
Gotcha, that makes sense. Thanks for explaining!
