### ISSUE TITLE
m7a.4xlarge is not supported in us-east-1a

### ISSUE THREAD

**Issue by alecmocatta** [runs-on/runs-on#5]
Using `runs-on,runner=16cpu-linux` from the README, having installed the CloudFormation stack in `us-east-1`, gives this error:

```text
WARN (probot): ⚠️ Failed to create instance with type m7a.4xlarge: Unsupported: Your requested instance type (m7a.4xlarge) is not supported in your requested Availability Zone (us-east-1a). Please retry your request by not specifying an Availability Zone or choosing us-east-1c, us-east-1d, us-east-1e, us-east-1f..
...
Error: Unable to start EC2 instance with the following configuration: {"imageSpec":{"owner":"135269210855","name":"runner-ubuntu22-*","user":"ubuntu","platform":"linux","arch":"x64"},"runnerSpec":{"cpu":16,"family":["c7a","m7a"]}}
```

The error email only gave the latter part of the error; I had to hunt around CloudWatch for the former.

Neither `m7a` nor `c7a` are (currently?) available in `us-east-1a`. `c6a` is though, and `runs-on,runner=16cpu-linux,family=c6a` spawns successfully.

**Edit:**

Though even `c6a` fails sporadically:
```text
WARN (probot): ⚠️ Failed to create instance with type c6a.4xlarge: InsufficientInstanceCapacity: We currently do not have sufficient c6a.4xlarge capacity in the Availability Zone you requested (us-east-1a). Our system will be working on provisioning additional capacity. You can currently get c6a.4xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1c, us-east-1d, us-east-1e, us-east-1f..
```

**Comment by crohr** [comment]
This is very surprising, since it used to work there. But you are correct (see below).

I can only assume they've run out for that type of instance in that first AZ and are waiting for more capacity?

```
aws ec2 describe-instance-type-offerings --location-type availability-zone  --filters Name=instance-type,Values=m7a.4xlarge --region us-east-1 --output table
-------------------------------------------------------
|            DescribeInstanceTypeOfferings            |
+-----------------------------------------------------+
||               InstanceTypeOfferings               ||
|+--------------+--------------+---------------------+|
|| InstanceType |  Location    |    LocationType     ||
|+--------------+--------------+---------------------+|
||  m7a.4xlarge |  us-east-1f  |  availability-zone  ||
||  m7a.4xlarge |  us-east-1c  |  availability-zone  ||
||  m7a.4xlarge |  us-east-1b  |  availability-zone  ||
||  m7a.4xlarge |  us-east-1e  |  availability-zone  ||
|+--------------+--------------+---------------------+|
```

**Comment by crohr** [comment]
v1.4.0 introduces AZ selection, so you can now choose to install RunsOn in an AZ that supports those instances.

**Comment by MisterJimson** [comment]
Should there be a way to leave the AZ blank? I got an error message that leaving it blank would have been able to spin up m7a.4xlarge

**Comment by crohr** [comment]
@MisterJimson What was the message? An instance has to be tied to a subnet, which itself is tied to an AZ, so currently an AZ has to be selected.

**Comment by MisterJimson** [comment]
It's the same as in this issue description. `...Please retry your request by not specifying an Availability Zone...`

`WARN (probot): ⚠️ Failed to create instance with type m7a.4xlarge: Unsupported: Your requested instance type (m7a.4xlarge) is not supported in your requested Availability Zone (us-east-1a). Please retry your request by not specifying an Availability Zone or choosing us-east-1c, us-east-1d, us-east-1e, us-east-1f..`

**Comment by crohr** [comment]
@MisterJimson Ah yes, so switch your stack to another AZ. Your current AZ does not have the latest hardware. This is normal, and we cannot know beforehand if say us-east-1a will have the latest hardware, because your us-east-1a is different than my us-east-1a since AWS maps a logical AZ to potentially different physical AZ underneath.

**Comment by MisterJimson** [comment]
Yeah I had it on us-east-1a, then swapped it to us-east-1b and saw the error again on b a little later.

Also, not sure the best way to change the AZ. In CloudFormation if I edit the AZ param in the runs-on stack, it doesn't trigger a changeset and so the param change isn't applied. Is there a better way to do it?

**Comment by crohr** [comment]
Make sure to always select "replace with a new template" even though it's the same. For some reason Cloudformation doesn't want to make a change set without it
