### ISSUE TITLE
Spot instance flag

### ISSUE THREAD

**Issue by ri-roee** [runs-on/runs-on#53]
Hey @crohr 

I noticed that there are two ways to enable/disable spot instances, one in `runs-on.yaml` [file](https://runs-on.com/features/custom-runners/) and the other directly in the `runs-on` [definition](https://runs-on.com/reference/spot-instances/). From crude testing it seems that only the later works, is this something that needs to be updated in the docs, or am I missing something? Thanks!

-Roee

**Comment by crohr** [comment]
Hi @ri-roee, which version? I will have a look tomorrow

**Comment by crohr** [comment]
And are you interested in the disabling case only I suppose?

Because otherwise an on-demand can be launched even if spot=true, in case no spot instances are available.

**Comment by ri-roee** [comment]
I think it was my fault actually - seems that when running on a branch the config defined on the `master` branch still wasn't getting picked up but when I defined it inline (i.e `runs-on,cpu=4+8+16,ram=16+32,family=m7i+m7a+c7i+c7a,hdd=150.,spot=false` it worked. Thanks for the quick response!
