### ISSUE TITLE
S3 Cache for Docker Builds Broken

### ISSUE THREAD

**Issue by ri-roee** [runs-on/runs-on#55]
Hey @crohr 👋🏼 

I think S3 cache for docker builds might be broken, am seeing this error with the following config:

```
#6 ERROR: operation error S3: GetObject, https response error StatusCode: 403,... api error AccessDenied: Access Denied
```

Config:
```
cache-from: type=s3,blobs_prefix=cache/,manifests_prefix=cache/,region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }}
cache-to: type=s3,blobs_prefix=cache/,manifests_prefix=cache/,region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }},mode=max
```

Not seeing anything in particular in Cloudtrail either and the IAM role looks good to me, wonder if the instances are not assuming role correctly?

**Comment by crohr** [comment]
Works for me! Are you maybe setting aws credentials in another action / environment? This could conflict with the default RunsOn environment variables. 

If not, could you share your workflow file maybe?
