### ISSUE TITLE
Unable to spin up ARM custom runners

### ISSUE THREAD

**Issue by ri-roee** [runs-on/runs-on#66]
When using the config `runs-on,cpu=4+8+16,ram=16+32,family=m7g+c7g,hdd=150` we are receiving the following error:

```
operation error EC2: CreateFleet, https response error StatusCode: 400, RequestID: 7b909e3b-21c6-4ad9-b2e1-a8290b7acb2b, api error InvalidParameterValue: We couldn't find any instance pools that match your instance requirements. Change your instance requirements, and try again.
```

Note that when using the default runners (`4cpu-linux-arm64`) this works fine. Thank you!

**Comment by crohr** [comment]
If you don’t specify a runner, you must give the image label `image=ubuntu22-full-arm64`

**Comment by ri-roee** [comment]
Odd because we do the same for non-ARM runners (`runs-on,cpu=4+8+16,ram=16+32,family=m7i+m7a+c7i+c7a,hdd=150`) and it works just fine?

**Comment by crohr** [comment]
Yes, the default image if none specified is `ubuntu22-full-x64`. So in your first case, AWS couldn't find instance types matching arm64 platform, but x64 image.

**Comment by ri-roee** [comment]
Makes sense, thank you!
