### ISSUE TITLE
Feature request: ability to add custom tags to the runners

### ISSUE THREAD

**Issue by michelesr** [runs-on/runs-on#67]
It would be nice to be able to add custom tags as labels. Custom tags are useful for example for cost allocation, e.g. determining how much a product is responsible for EC2 costs.

**Comment by crohr** [comment]
@michelesr are the default tags (`stack:runs-on`) not sufficient?

**Comment by michelesr** [comment]
> @michelesr are the default tags (`stack:runs-on`) not sufficient?

Well, we have different products that use runs-on to host jobs, and we would like to put the product name (or repository name) in the tags, so that in cost explorer you see which specific product is using runs-on instances and how much it costs.

**Comment by crohr** [comment]
Just to be clear: do you use a single RunsOn stack, or multiple?

Would it be sufficient if the repository full name was added as an instance tag? (it was there before, but has been removed while transitioning to the Go codebase).

**Comment by michelesr** [comment]
> Just to be clear: do you use a single RunsOn stack, or multiple?

Single stack

> Would it be sufficient if the repository full name was added as an instance tag? (it was there before, but has been removed while transitioning to the Go codebase).

I think that will be enough, as we'll be able to map the repositories to the products easily, and it won't require to set the labels on the workflow, so it will require no setup at all.

**Comment by crohr** [comment]
This is now available in https://github.com/runs-on/runs-on/discussions/70

**Comment by michelesr** [comment]
> This is now available in #70

I've installed v2.2.2 but I can't see the repo tag in the instances.

**Comment by crohr** [comment]
There are more than 10 tags, are you sure you went through all the pages in the UI? Could you send a screenshot maybe?

**Comment by michelesr** [comment]
> There are more than 10 tags, are you sure you went through all the pages in the UI? Could you send a screenshot maybe?

You're right, my bad.
