### ISSUE TITLE
Issues with auth when using S3 cache for docker layer caching and OIDC together

### ISSUE THREAD

**Issue by MatthewCane** [runs-on/runs-on#68]
Hello,

I am trying to use the S3 cache for docker layer caching as described [here](https://runs-on.com/reference/caching/), but I am getting an error message around auth which I suspect may be because I am using OIDC authentication in the same workflow. The workflow file in question contains the following:

```yaml
uses: docker/build-push-action@v5
with:
    cache-from: type=s3,blobs_prefix=cache/${{ github.repository }}/,manifests_prefix=cache/${{ github.repository }}/,region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }}
    cache-to: type=s3,blobs_prefix=cache/${{ github.repository }}/,manifests_prefix=cache/${{ github.repository }}/,region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }},mode=max
```

When I run this I am getting the following error message:

```text

#22 exporting cache to Amazon S3
#22 preparing build cache for export
#22 preparing build cache for export 85.6s done
#22 ERROR: failed to check file presence in cache: operation error S3: HeadObject, https response error StatusCode: 403, RequestID: <redacted>, HostID: <redacted>, api error Forbidden: Forbidden
------
 > importing cache manifest from s3:6106033539525829695:
------
------
 > exporting cache to Amazon S3:
------
ERROR: failed to solve: failed to check file presence in cache: operation error S3: HeadObject, https response error StatusCode: 403, RequestID: <redacted>, HostID: <redacted>, api error Forbidden: Forbidden
```

I am using OIDC to assume a role with permissions to push the image to ECR, so I presume there is an issue with the `docker/build-push-action` using the OIDC provided credentials rather than the EC2 instances credentials. Other than giving the OIDC role the necessary permissions to use the cache bucket, is there anything else I can do to get around this?

Thanks!

**Comment by crohr** [comment]
@MatthewCane Are you giving the OIDC role within the same `build-push-action` step? If so, you might try using 2 steps: one for building/tagging (with s3 cache), and one for pushing.

Otherwise yes you might need to amend the role to give access to the s3 cache bucket (on the `cache/` prefix).

**Comment by MatthewCane** [comment]
Yes that is correct, it's all being done within the same step. I'll try splitting it out or just granting additional permissions to the OIDC role. Thanks!
