### ISSUE TITLE
Using the S3 cache for docker get 403 errors

### ISSUE THREAD

**Issue by theophileds** [runs-on/runs-on#69]
I tired to set runs-on/cache for docker build using the following snipped:

```
- name: build-and-push
    uses: docker/build-push-action@v5
    with:
        cache-from: type=s3,blobs_prefix=cache/${{ github.repository }}/,manifests_prefix=cache/${{ github.repository }}/,region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }}
        cache-to: type=s3,blobs_prefix=cache/${{ github.repository }}/,manifests_prefix=cache/${{ github.repository }}/,region=${{ env.RUNS_ON_AWS_REGION }},bucket=${{ env.RUNS_ON_S3_BUCKET_CACHE }},mode=max
        platform: linux/amd64
        push: true
```

But it failed with the following error:

```
#21 ERROR: failed to check file presence in cache: operation error S3: HeadObject, https response error StatusCode: 403, RequestID: XNZZZZ558YJRBSNV, HostID: btBnnja9avsAw6ew57JHS7kiJQH99DUGkpiKJSHAKJSHAKSHUgeJwSSiPcz1i8WrCnfuPegXmEWg=, api error Forbidden: Forbidden
------
 > importing cache manifest from s3:17484568996900153046:
------
------
 > exporting cache to Amazon S3:
------
ERROR: failed to solve: failed to check file presence in cache: operation error S3: HeadObject, https response error StatusCode: 403, RequestID: XNJJDH554YJRBSNV, HostID: btBnnja9avsAw6ew57UEJ7kiJQH99DUGkpi0EPAPYJHKjdJHDGSGEGiPcz1i8WrCnfuPegXmEWg=, api error Forbidden: Forbidden
```

**Comment by crohr** [comment]
Hello, you most likely have set up alternative AWS credentials in a previous step, which are overriding the EC2 instance profile set on the runner. Could you share your workflow file maybe?

**Comment by theophileds** [comment]
I've been a little fast here!

So how to do you reconcile pushing images to ECR registry and using cache?

**Comment by crohr** [comment]
@theophileds What does your push step look like? Also see #68 if you use the `docker/build-push-action` action.

**Comment by crohr** [comment]
Yes I think that's the best way. Split the build and push phases in two.

Or you could also specify a custom IAM policy in your CloudFront stack, to allow pushing docker images transparently so no need to configure AWS credentials.

See the `official_image_with_preinstall` image definition in https://runs-on.com/features/byoi/ for an example of using the runner IAM instance profile credentials to transparently log into ECR before a job starts.

**Comment by GreyTeardrop** [comment]
We've faced the same issue. The workaround we took is to reset the credentials set by `aws-actions/configure-aws-credentials` right after the `aws-actions/amazon-ecr-login`:
```yaml
      - name: Unset AWS credentials after ECR login
        run: |
          echo 'AWS_ACCESS_KEY_ID=' >> $GITHUB_ENV
          echo 'AWS_SECRET_ACCESS_KEY=' >> $GITHUB_ENV
          echo 'AWS_SESSION_TOKEN=' >> $GITHUB_ENV
          echo 'AWS_DEFAULT_REGION=' >> $GITHUB_ENV
          echo 'AWS_REGION=' >> $GITHUB_ENV
```

**Comment by crohr** [comment]
@GreyTeardrop note that in your case, you can also use the unset credentials option of the configure-aws-credential option

**Comment by GreyTeardrop** [comment]
Interesting! I did not realize it's possible to call `configure-aws-credential` just to unset existing credentials in the env without setting any new ones. Thank you!
