### ISSUE TITLE
InsufficientInstanceCapacity leads to hanging Action

### ISSUE THREAD

**Issue by Reregistered** [runs-on/runs-on#73]
Many times a day we are getting a message similar to:

```We currently do not have sufficient m7a.xlarge capacity in the Availability Zone you requested (us-east-1c). Our system will be working on provisioning additional capacity. You can currently get m7a.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1b, us-east-1d, us-east-1f.```

Which results in our action hanging with the following message.

```
Requested labels: runs-on,runner=4cpu-linux-x64,run-id=8911589573
Job defined at: ToricLabs/main/.github/workflows/main.yml@refs/pull/13209/merge
Waiting for a runner to pick up this job...
```

As far as I can tell it will never get retried, I have to manually cancel the run and retry. 

----

I will try to mitigate this issue via a custom runner configuration with more instance types, but wondering around two other potential mitigations:

1 - It looks like Availability Zone is specified in the runner config ( per setup job) ?

```
Runner Instance
  |       INFO        |                    VALUE                    |
  |-------------------|---------------------------------------------|
  | SSH               | ssh runner@54.221.153.199                   |
  | Admins            | [Reregistered thiagocosta3d]                |
  | Region            | us-east-1                                   |
  | AvailabilityZone  | us-east-1c                                  |
  | Version           | v2.2.2                                      |
  | Runner            | runs-on--i-0b5bb11b162a1355b--lMeKXDhYta    |
```

Can this be exposed and specified as a runner config? If one isn't specified should it be left empty?

2 - Is there a way to automatically fail and retry after a period?

thanks, let me know if other info would be useful.

**Comment by crohr** [comment]
Hello,

RunsOn asks for a spot instance across all availability zones at once, and AWS takes care of finding a spot instance in one of them. With the default runner types you should almost always find an m7i or m7i-flex as a fallback to m7a, but maybe your account ended up on underprovisioned AZs, although this would be surprising for us-east-1. Is this a new AWS account?

RunsOn will attempt to retry at most 5 times in case the instance could not be launched. If you can send me an export of the CloudWatch logs for the AppRunner application, filtered with the `run-id` number, I could check what happened end there (cyril AT runs-on.com)

**Comment by Reregistered** [comment]
Hi @crohr 

Thanks for taking a look at the logs. As discussed this is likely user error where a few PR's have been opened specifying a specific family of instance types.  Not an issue.
