### ISSUE TITLE
Workflow jobs no longer run

### ISSUE THREAD

**Issue by kevin-poitra** [runs-on/runs-on#76]
As of the past few days, any workflow jobs I've setup no longer run. In particular, the last successful run was on Tuesday of this week. I hadn't run any workflows since then, but as of today, nothing will run. I was originally on v2.2.0 and upgraded to v2.2.2, but that didn't make the workflows start running.

Here's some things I've observed:

- Runs-On will create logs stating that it sees the workflow, it parses the desired EC2 config successfully, and even states "Runner scheduled successfully" and "Successfully deleted message from the SQS queue".

- EC2 instances do get spun up, but after a minute or two, they're terminated without ever having run the workflow.

That's all I'm able to discern from the CloudWatch logs. Let me know if there's any further logs that can assist with figuring this out.

**Comment by crohr** [comment]
Hello, can you send your logs to cyril@runs-on.com? Thanks!

**Comment by kevin-poitra** [comment]
I've just sent you the Runs-On application logs filtered down to a workflow run that I just attempted. If it helps make it clearer, there's three testing workflows as part of this job, and all three are stuck waiting for a runner to run them.

**Comment by pvande** [comment]
For what it's worth, my team is seeing this same thing.

**Comment by crohr** [comment]
@pvande the underlying issue was an incorrect custom image definition. What are you seeing in your case? Can you send logs or screenshots to cyril@runs-on.com ?

**Comment by pvande** [comment]
I'll be happy to when I get a chance; I've been away from work for the last week and a half.

**Comment by crohr** [comment]
Ok, I added a video showing how to view the logs in CloudWatch - https://runs-on.com/guides/troubleshoot/#view-the-application-logs

I’m closing this for now, we’ll continue in private.

**Comment by crohr** [comment]
@pvande if your runners are using a custom or non-`full` image, it might be due to the runner binary being out of date. This will be fixed in #78 but in the meantime I would encourage you to use `ubuntu22-full-[x64|arm64]` instead.
