### ISSUE TITLE
Support using a Terraform module instead of cloudformation?

### ISSUE THREAD

**Issue by pksunkara** [runs-on/runs-on#80]
All our infra is in Terraform and thus would like to use it for this too instead of AWS CF. I am not sure if you are doing something in the cloudformation that can't be done using terraform. If yes, please let me know and I can look into alternatives.

**Comment by crohr** [comment]
@pksunkara you can easily use terraform to provision the CF stack. I don't think you want to go into reimplementing the whole stack with the native terraform primitives.

I can send you an example if you want.

**Comment by pksunkara** [comment]
@crohr Thanks for the response. While what you said is a workaround, I prefer a terraform module instead of a CF stack. Therefore, I want to understand your reasons for why it can't be a terraform module. Is there any capability in CF that can't be done with a terraform module?

Please don't misunderstand me, I am just trying to wrap my head around the choice here.

**Comment by crohr** [comment]
@pksunkara Reasons for using CloudFormation and not terraform:

- 1-click install / 1-click upgrades (see demo video on runs-on.com)
- declarative, and AWS ensures convergence vs hopefully terraform plans and converges as expected
- preview changesets easily, view outputs easily in a UI

All in all, CloudFormation has been a godsend for that project, 10/10 would use it again.

**Comment by crohr** [comment]
Again I'm not sure what terraform would bring to the project. If you really want to manage the stack with terraform, just import the CF template and use terraform to launch the stack provisioning.
