### ISSUE TITLE
Feature Request: label for CPU architecture

### ISSUE THREAD

**Issue by colstrom** [runs-on/runs-on#86]
First off, thanks for `runs-on`. It makes my life easier, and I appreciate the work that's gone into it.

I'm encountering a similar issue to #66, but when specifying ONLY the image. With the following labels:
```
* Labels: [runs-on,image=ubuntu22-full-arm64,run-id=9308315327]
```

I get this error:
```
operation error EC2: CreateFleet, https response error StatusCode: 400, RequestID: fd945d53-9f49-49ac-a59b-bd2e38ddb87d, api error InvalidParameterValue: We couldn't find any instance pools that match your instance requirements. Change your instance requirements, and try again.
```

It works fine if I specify `family=` or `runner=`, which seems to suggest that it's defaulting to `x64` unless it has a reason not to.

`family=` restricts the selection criteria considerably, so isn't ideal as a workaround, and `runner=` can lead to some... awkward label combos like:

```yaml
runs-on: runs-on,runner=1cpu-linux-arm64,cpu=4,image=ubuntu22-full-arm64
```

Exposing some sort of `arch=` selector could help with this, if I'm understanding the problem correctly. The above would be expressed as:

```yaml
runs-on: runs-on,arch=arm64,cpu=4,image=ubuntu22-full-arm64
```

or even as:

```yaml
runs-on: runs-on,arch=arm64,cpu=4
```

Which would provide enough context to filter the instance types and images accordingly (since `ubuntu22-full-*` is already the default, and only being specified as a way to request an ARM runner).

Thanks for taking the time to consider this request. I hope it fits into the intended use of the program well enough to warrant inclusion.

❤️

**Comment by crohr** [comment]
> `runs-on: runs-on,runner=1cpu-linux-arm64,cpu=4,image=ubuntu22-full-arm64`

Why not simply use `runs-on: runs-on,runner=4cpu-linux-arm64` ?

**Comment by crohr** [comment]
I see, but `runner` should always be specified, because that's the one setting the family possible types, which may vary according to the number of CPUs required by that `runner` type. For instance, runner types with high CPU count (>=8) will prioritise `c*` families instead of `m*`.

Really the best way to define your runners should always be with the `runner` type, followed by specific `family` types (e.g. `family=m7i+m7a+...`) if you want to override them. If you are not using custom images, you should never need to specify the `image` label.

```
runs-on: runs-on,runner=4cpu-linux-x64
runs-on: runs-on,runner=4cpu-linux-x64,family=m7i+m7a
runs-on: runs-on,runner=4cpu-linux-arm64
runs-on: runs-on,runner=4cpu-linux-arm64,family=m7g
```

**Comment by colstrom** [comment]
Potentially related, this label combination:

```
* Labels: [runs-on,image=ubuntu22-full-x64,cpu=4,ram=32,run-id=9309141351]
```

Yields the following error:

```text
runner label `` not found. (If you are using a configuration file, make sure the file is in the main branch. This could also be due to an error when fetching the file from the GitHub API)
```

**Comment by crohr** [comment]
> `runner label `` not found`

Can you share your workflow yaml definition? If no `runner` label provided, it should always default to `2cpu-linux-x64`, so I think your workflow file might have an issue.

**Comment by colstrom** [comment]
> I see, but `runner` should always be specified, because that's the one setting the family possible types, which may vary according to the number of CPUs required by that `runner` type. For instance, runner types with high CPU count (>=8) will prioritise `c*` families instead of `m*`.

Oh! That's interesting. I wasn't aware that `runner` was required. I'm confused what the purpose of the `cpu` label is, then. Is it just for narrowing the selection **within** the candidate instance types that `runner` starts from?

**Comment by colstrom** [comment]
> > `` runner label `` not found ``
> 
> Can you share your workflow yaml definition? If no `runner` label provided, it should always default to `2cpu-linux-x64`, so I think your workflow file might have an issue.

Sure, I'll strip it down to a minimum reproducible example, since there's a bunch of other nonsense in there that's not related to this. 😁

**Comment by crohr** [comment]
`cpu` can be used to extend the selection. For instance you might want `4cpu-linux-x64` as base, but are also ok with machines with 8 cpus if they're somehow cheaper, so you would add `cpu=4+8`. Could be useful in some cases where you have a wide variety of `family` types.

But again, you should probably stick to the default `runner` types, and only override `family` if needed.

**Comment by crohr** [comment]
> Sure, I'll strip it down to a minimum reproducible example, since there's a bunch of other nonsense in there that's not related to this. 😁

Hmm actually looking at the code, if you specify `cpu` or `ram` AND no `family`, then indeed the error is triggered because RunsOn cannot proceed.

**Comment by colstrom** [comment]
This is enough to reproduce it:

```yaml
---
name: Runs-On Minimum Reproduction
on: push
jobs:
  example:
    runs-on: runs-on,image=ubuntu22-full-x64,cpu=4,ram=32,run-id=${{ github.run_id }}
    steps:
    - run: |
        grep '' /etc/os-release /proc/cpuinfo /proc/meminfo /proc/partitions
        uname -a
        lsblk --list
```

**Comment by colstrom** [comment]
> > Sure, I'll strip it down to a minimum reproducible example, since there's a bunch of other nonsense in there that's not related to this. 😁
> 
> Hmm actually looking at the code, if you specify `cpu` or `ram` AND no `family`, then indeed the error is triggered because RunsOn cannot proceed.

So this is kind of what I was thinking with `arch` as a label or something of the sort.

In my head, the most desirable constraints to express are:

- cpu architecture (sometimes, but it's a pretty hard one to avoid)
- minimum memory (more is fine, if it's cheaper, and spot pricing is wild enough that it often is cheaper to get more)
- minimum cpu cores (again, more is usually fine)
- minimum storage.
- a custom image (sometimes)

And like... _maybe_ maximums on some of those things, for testing against resource-constrained environments or something.

`runs-on` covers most of this stuff, or close enough at least. `runner=` feels like a sane predefined shape. I'm still wrapping my head around how it composes with the other labels, but I think that says more about **my understanding** than it does about `runs-on` in any way. 😆

The `hdd=` label is a bit weird, since it sort of implies more flexibility than it offers. I assume this has something to do with the connection between volume throughput and storage capacity? The documentation does state that it only allows selecting between two predefined sizes chosen at deployment/configuration time, so that's fair enough.

The `family=` label on the other hand, seems more relevant the folks managing infrastructure (hi! that's me!), and less so for the folks running their workflows on that infrastructure. I mean, there's definitely cases where it's a valuable selector, like hardware-specific testing and such, but Amazon has like... 700+ different instance types, the existence of which varies **by availability zone**. I suspect that the majority of times it's being set, it's actually being used as a proxy for some other selection criteria like `arch` or `hypervisor` or `network-performance` or something. But in fairness, that is a guess. I don't have hard data to support that claim.

For what it's worth, I use [`ec2-instance-selector`](https://github.com/aws/amazon-ec2-instance-selector) and [`karpenter`](https://github.com/aws/karpenter-provider-aws) in other contexts, so those are partially shaping my mental model of instance selection. I know it may not translate perfectly to the limitations of GitHub's label system, and that balancing configurability with ease of use is a challenge on its own.

Thanks!

**Comment by crohr** [comment]
> The hdd= label is a bit weird

Yes, it used to allow full flexibility in term of disk size, but with the switch to `CreateFleet` API I had to use predefined launch templates so there are now only 2 possible variants. Works well enough for the majority of use cases though, but I agree it might be a bit confusing.

> The family= label on the other hand, seems more relevant the folks managing infrastructure

I think it is useful to keep it exposed to developers (that would be me!), because some families perform better for certain kinds of workflows, and it's good to be able to experiment with family selection without the need to reconfigure the stack. For those not especially interested, the `runner` types should cover most use cases, and could even be centrally redefined by the ops people using the `runs-on.yaml` configuration file in a central repository.

That being said, there is probably some improvements to be made here, and the combination of `runner` + `image` can be a bit verbose sometimes. One thing that I will probably change is that specifying `cpu=4` should actually ask for `cpu=[4..Inf]` instead of having to specify `cpu=4+8+16+...` because as you say I can't think of any case where it would be detrimental to get a higher-spec runner if the spot price is lower. Same for `ram`.

**Comment by colstrom** [comment]
> > The hdd= label is a bit weird
> 
> Yes, it used to allow full flexibility in term of disk size, but with the switch to `CreateFleet` API I had to use predefined launch templates so there are now only 2 possible variants. Works well enough for the majority of use cases though, but I agree it might be a bit confusing.
> 

That makes sense, I can see how it got that way. And changing the parameter name to something like `storage-kind` or something would be incompatible with prior versions, so that's a delicate thing to muck about with when docs can explain it just fine.

> > The family= label on the other hand, seems more relevant the folks managing infrastructure
> 
> I think it is useful to keep it exposed to developers (that would be me!), because some families perform better for certain kinds of workflows, and it's good to be able to experiment with family selection without the need to reconfigure the stack. For those not especially interested, the `runner` types should cover most use cases, and could even be centrally redefined by the ops people using the `runs-on.yaml` configuration file in a central repository.
> 

Oh, for sure. I didn't mean to imply that things should be taken away (I'm a big fan of "sane defaults, but let the user override whatever they want at their own peril" approach). What I meant to suggest was that I'd like to see some of the underlying things exposed that that setting may be a proxy for.

> That being said, there is probably some improvements to be made here, and the combination of `runner` + `image` can be a bit verbose sometimes. One thing that I will probably change is that specifying `cpu=4` should actually ask for `cpu=[4..Inf]` instead of having to specify `cpu=4+8+16+...` because as you say I can't think of any case where it would be detrimental to get a higher-spec runner if the spot price is lower. Same for `ram`.

The _two_ scenarios I can think of is testing in deliberately constrained environments, and benchmarking. But as long as there's a way to specify an upper bound, having it default to "at least this" seems very reasonable to me.

**Comment by crohr** [comment]
> The two scenarios I can think of is testing in deliberately constrained environments, and benchmarking. But as long as there's a way to specify an upper bound, having it default to "at least this" seems very reasonable to me.


So currently there is no longer a way to set an upper bound, but you can always specify the full `family` name if you want a specific instance type. I think it's ok. I have updated the [doc](https://runs-on.com/features/custom-runners/#available-runs-on-labels) to reflect the change.

I'm keeping the `arch` idea in my mind, maybe I'll come back to it at some point.

Thanks for the discussion!
