### ISSUE TITLE
CreateFeet error: "MaxFleetCountExceeded"

### ISSUE THREAD

**Issue by danielsantiago** [runs-on/runs-on#88]
I'm getting an error that I can't find documentation anywhere on how to resolve it. This is the first time the error appears after more than 3 weeks of using the service.

```
operation error EC2: CreateFleet,
https response error StatusCode: 400,
RequestID: 3e9fe392-f4a6-4499-8c1b-54e5c903a0ba,
api error MaxFleetCountExceeded:
You've reached your quota for maximum Fleet Requests for this account.
```

**Comment by crohr** [comment]
@danielsantiago hmm, first time I see this as well. Any idea how many requests you runners you had started during the last hour?

**Comment by danielsantiago** [comment]
When I try to create a spot instance manually from the AWS Console this is the error I get: "You've reached your quota for maximum Spot Fleet Requests for this account."

**Comment by crohr** [comment]
I'm assuming this is an issue on AWS side, especially if it just started returning client error for no reason. Can you raise the issue with your account manager / tech support maybe? Which region are you on?

**Comment by danielsantiago** [comment]
I'm on us-east-1.

**Comment by danielsantiago** [comment]
It seems to be part of the AWS quota limits for Spot Instances, but shouldn't Runs-on then try to use On-demand instances in these cases?

![CleanShot 2024-06-10 at 11 33 49](https://github.com/runs-on/runs-on/assets/619122/59c81cac-afa6-4278-be31-6aca1c2c5453)
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html

**Comment by crohr** [comment]
RunsOn currently switches to on-demand if you get the `MaxSpotInstanceCountExceeded` error. `MaxSpotFleetRequestCountExceeded` is not specifically processed (but probably should). But it still doesn't make sense that you're getting this error if you're basically running no instance.

What's your current quota for `All Standard (A, C, D, H, I, M, R, T, Z) Spot Instance Requests` (https://us-east-1.console.aws.amazon.com/servicequotas/home/services/ec2/quotas/L-34B43A08) ?

**Comment by crohr** [comment]
Does it work if you specify `spot=false` in your `runs-on: ` definition?

**Comment by danielsantiago** [comment]
> What's your current quota for `All Standard (A, C, D, H, I, M, R, T, Z) Spot Instance Requests` ([us-east-1.console.aws.amazon.com/servicequotas/home/services/ec2/quotas/L-34B43A08](https://us-east-1.console.aws.amazon.com/servicequotas/home/services/ec2/quotas/L-34B43A08)) ?

My quota is: 500

![CleanShot 2024-06-10 at 12 01 27](https://github.com/runs-on/runs-on/assets/619122/5e2822db-c1e0-4436-9cf5-6fbfc026a0e7)

> Does it work if you specify `spot=false` in your `runs-on: ` definition?

I'm going to try this

**Comment by danielsantiago** [comment]
Now I'm seeing errors in other parts of the AWS console and I'm getting this error: "This account is suspended." Sorry, I would have liked the error to be clearer from the beginning so as not to waste your time. At least you now have a reference to this error for a future occasion. Anyway, once I resolve it with AWS support, I will update this issue in case it can help someone in the future.

**Comment by crohr** [comment]
No problem, I learned something. Hopefully you can sort it out soon.
