### ISSUE TITLE
Failed to create instance with type c7a.large: InvalidParameterValue: User data is limited to 16384 bytes.

### ISSUE THREAD

**Issue by TimPetricola** [runs-on/runs-on#9]
I'm experimenting with `runs-on` and the project looks very promising!

However I'm getting an error when the service tries to create the EC2 instance:

```
WARN (probot): ⚠️ Failed to create instance with type c7a.large: InvalidParameterValue: User data is limited to 16384 bytes.

Error: Unable to start EC2 instance with the following configuration: 
{
    "imageSpec": {
        "platform": "linux",
        "arch": "x64",
        "name": "runner-ubuntu22-*",
        "owner": "135269210855",
        "user": "ubuntu"
    },
    "runnerSpec": {
        "cpu": 2,
        "family": [
            "m7a",
            "c7a"
        ]
    }
}
```

It happens while I have a very simpler config, with only change being:

```
- runs-on: runs-on,runner=2cpu-linux
```

Does that ring a bell by any chance?

**Comment by crohr** [comment]
I wonder if this is due to many repo collaborator ssh keys being added into the user data script. Could you try with `ssh=false` in addition to the other labels?

**Comment by TimPetricola** [comment]
@crohr indeed that was it, thanks for your reactivity 🙏

**Comment by crohr** [comment]
I'll fix this in another release. I think `ssh` will simply take a list of GitHub usernames instead of defaulting to all members with push permission.
