### ISSUE TITLE
Jobs hanging with message `Waiting for a runner to pick up this job...`

### ISSUE THREAD

**Issue by MatthewCane** [runs-on/runs-on#98]
Firstly, thank you for this awesome project!

I have an intermittent error which I have been unable to resolve on my own. One of our workflows creates 10 instances in a matrix in order to run a massive test suite in parallel. On maybe 10% or 15% of the runs one or more of the matrix jobs will be left hanging with `Waiting for a runner to pick up this job...` in the log. It will do this indefinitely until someone cancels the job and restarts it which almost always fixes the issue. This causes a lot of issues for us as a hanging job will block our continuous deployment workflow until it is noticed and manually resolved.

I have checked the logs `runs-on` AppRunner logs during one of these events and there is no errors or anything else that looks out of the ordinary. I have also not seen any warnings or errors from AWS to do with rate-limiting or anything like that. I have, however, set a very specific `runs-on` label for these jobs:

```yaml
runs-on: runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }},matrix-index=${{ matrix.tests.index }}
```

The matrix index is just an integer so I can identify the test groups. This has allowed me to more easily pinpoint one of these problem instances in the EC2 console. When I look up the `runs-on-labels` tag, I can actually see two EC2 instances that match that label where I would expect to only see one. The instances have startup times 2 minutes apart. I described them in the console and I can see only a few differences that might make a difference. I have attached the instance details below with some info redacted (if you need the full unredacted details I could sent them in a private channel):

[instance-i-044fae94291e671e4.json](https://github.com/user-attachments/files/15984109/instance-i-044fae94291e671e4.json)
[instance-i-0356d44e11c712376.json](https://github.com/user-attachments/files/15984110/instance-i-0356d44e11c712376.json)

I am not sure if this is something that is expected. I am quite stumped on this, so if you need any more info please let me know!

Many thanks.

**Comment by crohr** [comment]
Hi @MatthewCane, this is not normal, but you should upgrade to the latest version, which fixes an issue for dangling instances in some cases. Could you confirm wether you received errors by email or not?

**Comment by MatthewCane** [comment]
Thank you for the super quick response! I am on `v2.3.1` so I will upgrade to `v2.3.2` and closely monitor the workflows today. I'll close the ticket if this patch fixes the issue 👍

**Comment by MatthewCane** [comment]
It doesn't look like that has resolved the issue, a deployment this morning has two jobs hanging for 30 minutes so far.

**Comment by crohr** [comment]
@MatthewCane can you fetch the instance id of the pending runners, and send the cloud-init-output logs to cyril@runs-on.com ?

https://runs-on.com/guides/troubleshoot/#view-the-instance-logs

**Comment by crohr** [comment]
The fact that it spawns 2 instances at 2min interval suggests that the first instance creation was seen as an error, and then retried 2min later. You should see an error message in the AppRunner logs, and it should have been sent as an error by email, if you are subscribed to the SNS topic. Just to be sure, have you searched across the whole log group (https://runs-on.com/guides/troubleshoot/#view-the-application-logs)?

You could also send me an export of the AppRunner logs for the relevant time interval, so that I can have a look.

**Comment by MatthewCane** [comment]
I've sent you an email with the logs you requested and some additional findings.

**Comment by maximepiton** [comment]
Hi!

FYI We notice the same behaviour on our side. I retried 3 times a workflow, and each time one job got stuck.
We also use v2.3.2, and nothing shocking in AppRunner logs.

I don't know if that's related or not, but I noticed a few instances that apparently failed to init properly, with a lot of `Waiting for tags file to be present...` entries in cloud-init logs, until they reached the 10min timeout and got ripped off.

**Comment by crohr** [comment]
@maximepiton do you have the run-id label as part of your runs-on definition? The underlying issue here was that a runner with a subset of labels would pick up a runner with more labels that was dedicated to another job.

**Comment by MatthewCane** [comment]
Following up now the issue has been resolved for those that find this issue:

As I understand it the problem was with how Actions jobs are matched with EC2 instances using their labels. A job with the labels `a,b,c` will match with instances with labels `a,b,c` but also `a,b,c,d`, so there is a possibility a job with less specific labels will 'steal' an instance from a job with more specific labels.

The fix was to make sure each job was thoroughly labeled to ensure it was unique. For example, I have updated our jobs to use some variation of the following label:

```yaml
runs-on: runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }},job=job-name
```

And with matrix jobs I have added an additional label to make it unique within the matrix group using a key from the matrix definition.

I hope this helps and please feel free to correct my assumptions here @crohr
